title: NP Digital Services
url: https://www2.np.edu.sg
favicon: /images/Banner and Logo/favicon_isomer.ico
colors:
  primary-color: "#414142"
  secondary-color: "#004689"
  media-colors:
    - title: media-color-one
      color: "#fbb040"
    - title: media-color-two
      color: "#fbb040"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: The NP Digital Services portal serves as a central informational
  site for students accessing IT resources, including software download,
  notebook requirements, FAQs, quick links, guides, and more. It’s your go-to
  place for all things related to digital services at Ngee Ann Poly!
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging-lite.d2n20hb5wi6675.amplifyapp.com
prod: https://master.d2uc18hc4h2ycw.amplifyapp.com
facebook-pixel: ""
shareicon: /images/Banner and Logo/favicon_isomer.ico
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
resources_name: queries
